# Generated by Django 6.0.1 on 2026-03-01 20:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ESP32Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('serial_port', models.CharField(blank=True, help_text='e.g., /dev/ttyUSB0 or COM3', max_length=50)),
                ('baud_rate', models.IntegerField(default=9600)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='monitoring.sector')),
            ],
            options={
                'verbose_name': 'ESP32 Device',
                'verbose_name_plural': 'ESP32 Devices',
                'ordering': ['sector__name'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(help_text='CO or Temperature', max_length=50)),
                ('current_level', models.FloatField()),
                ('predicted_level', models.FloatField()),
                ('time_to_reach', models.IntegerField(help_text='Minutes until predicted level')),
                ('severity', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('recommendation', models.TextField()),
                ('model_used', models.CharField(default='risk_model.joblib', max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='monitoring.sector')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='monitoring__timesta_4b4453_idx'), models.Index(fields=['sector', '-timestamp'], name='monitoring__sector__76e136_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('co_high', 'High CO Level'), ('temp_high', 'High Temperature'), ('sensor_failure', 'Sensor Failure'), ('prediction_critical', 'Critical Prediction')], max_length=30)),
                ('severity', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.sector')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='monitoring__created_1b6598_idx'), models.Index(fields=['status', '-created_at'], name='monitoring__status_4b15ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_monoxide', models.FloatField(help_text='CO level in ppm')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Raw sensor data from ESP32', null=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitoring.sector')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='monitoring__timesta_97dc13_idx'), models.Index(fields=['sector', '-timestamp'], name='monitoring__sector__1e4d47_idx')],
            },
        ),
    ]
